<?php

namespace AppBundle\Repository;

/**
 * ResultAuditRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuditRepository extends \Doctrine\ORM\EntityRepository
{
            
    public function findByEnvDetailsIdAndParamId($envDetailsId,$productParameterId)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT a,ed,pp FROM AppBundle:Audit a 
                JOIN a.envDetails ed
                JOIN a.productParameter pp
                WHERE ed.id = :envDetailsId 
                AND pp.id = :productParameterId'
            )->setParameter('envDetailsId', $envDetailsId)
             ->setParameter('productParameterId', $productParameterId)
                ;
        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }    
    
}
