<?php

namespace AppBundle\Repository;

/**
 * ResultAuditRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuditRepository extends \Doctrine\ORM\EntityRepository
{
            
    public function findByEnvDetailsIdAndParamId($envDetailsId,$productParameterId)
    {
        
        //TODO adapt with date
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT a,ed,pp FROM AppBundle:Audit a 
                JOIN a.envDetails ed
                JOIN a.productParameter pp
                WHERE ed.id = :envDetailsId 
                AND pp.id = :productParameterId
                ORDER BY a.id desc'
            )->setMaxResults(1)
             ->setParameter('envDetailsId', $envDetailsId)
             ->setParameter('productParameterId', $productParameterId)
                ;
        try {
            $result = $query->getSingleResult();
            if ($result != null) 
            {
                return $result;
            }
            else
            {
                return null;
            }
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }    
    
}
