<?php

namespace AppBundle\Repository;

/**
 * EnvDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnvDetailsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllOrderedByServerCategory()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT ed, sc, e, s FROM AppBundle:EnvDetails ed 
                JOIN ed.servercategory sc
                JOIN ed.environment e
                JOIN ed.server s
                ORDER BY ee.servercategory ASC'
            )
            ->getResult();
    }    
    
    public function findAllByEnvId($Id)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT ed, e, s,sc FROM AppBundle:EnvDetails ed
                JOIN ed.environment e
                JOIN ed.server s
                JOIN ed.servercategory sc
                WHERE e.id = :id'
            )->setParameter('id', $Id);
        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
    /*
    public function findById($envid)    
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT ed, e, s FROM AppBundle:EnvDetails ed
                JOIN ed.environment e
                JOIN ed.server s
                WHERE ed.id = :id'
            )->setParameter('id', $Id);
        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }        
    }
     * 
     */
    

    
/*    
    public function findOneByIdJoinedToEnvironment($Id)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT ed, e FROM AppBundle:EnvDetails ed
                JOIN ed.environment e
                WHERE ed.id = :id'
            )->setParameter('id', $Id);
var_dump($query->getSQL());

        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }    
*/    
    
}
