<?php

namespace AppBundle\Repository;

/**
 * ResultAuditRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultAuditRepository extends \Doctrine\ORM\EntityRepository
{
}
