<?php

namespace AppBundle\Repository;

/**
 * ServerCategoryTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServerCategoryRepository extends \Doctrine\ORM\EntityRepository
{
    
   public function findAllOrderedByName()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT sc FROM AppBundle:ServerCategory sc 
                    ORDER BY sc.name ASC'
            )
            ->getResult();
    } 
}
