<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * ServerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServerRepository extends EntityRepository
{
   public function findAllOrderedByName()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT s FROM AppBundle:Server s ORDER BY s.name ASC'
            )
            ->getResult();
    }        
}
