<?php

namespace AppBundle\Repository;

/**
 * ServerCategoryTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServerCategoryRepository extends \Doctrine\ORM\EntityRepository
{
    
   public function findAllOrderedByName()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT sc FROM AppBundle:ServerCategory sc 
                    ORDER BY sc.name ASC'
            )
            ->getResult();
    } 
    
    
    public function findAllByProductId($productId)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT sc FROM AppBundle:ServerCategory sc 
                JOIN sc.product p
                WHERE p.id = :productId'
            )->setParameter('productId', $productId);
        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }    
}
