<?php

namespace AppBundle\Repository;

/**
 * ServerTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServerTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
